Emulators:
  Pixel_3_XL_API_30:
    deviceName: Android
    udid: emulator-5554
    platformName: Android
    platformVersion: !!str 11
    newCommandTimeout: 0
    noReset: !!str true
    printPageSourceOnFindFailure: !!str true
    appPackage: com.bcy.fsapp
    appActivity: com.bcy.fsapp.activity.MainActivity

  Pixel_4_XL_API_30:
    deviceNmae: Android
    udid: emulator-5556
    platformName: Android
    platformVersion: !!str 11
    newCommandTimeout:  0
    noReset: !!str true
    printPageSourceOnFindFailure: true
    appPackage: com.bcy.fsapp
    appActivity: com.bcy.fsapp.activity.MainActivity

Adresses:
  - !!str http://127.0.0.1:4723/wd/hub
  - !!str http://127.0.0.1:4724/wd/hub

Loggers:
  LOGGING_INFO_CONFIG:
    version: 1
    disable_existing_loggers: False
    formatters:
      default_formatter:
        format : !!str "[%(levelname)s:%(asctime)s] %(message)s"
    handlers:
      stream_handler:
        class: logging.StreamHandler
        formatter: default_formatter
    loggers:
      my_logger:
        handlers:
        - stream_handler
        level: INFO

DB:
  user: doadmin
  password: AVNS_PFjq5toTIGUPXDHv46B
  host: stepn-parser-db-do-user-11931400-0.b.db.ondigitalocean.com
  port: 25060
  database: defaultdb
  raise_on_warnings: True